apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: demo-api
  description: The demo API based on publicly open WeatherDB API
  tags:
    - rest
  links:
    - url: https://weatherdbi.herokuapp.com/documentation/v1
      title: Documentation
      icon: docs
    - url: https://weatherdbi.herokuapp.com/
      title: Home page
      icon: docs
spec:
  type: openapi
  lifecycle: experimental
  owner: team-a
#  system: 
  definition: |
    openapi: "3.0.0"
    info:
    version: 1.0.0
    title: Swagger Demo-API
    license:
        name: MIT
    servers:
    - url: http://petstore.swagger.io/v1
    paths:
    /pets/{petId}:
        get:
        summary: Info for a specific pet
        operationId: showPetById
        tags:
            - pets
        parameters:
            - name: petId
            in: path
            required: true
            description: The id of the pet to retrieve
            schema:
                type: string
        responses:
            '200':
            description: Expected response to a valid request
            content:
                application/json:
                schema:
                    $ref: "#/components/schemas/Pet"
            default:
            description: unexpected error
            content:
                application/json:
                schema:
                    $ref: "#/components/schemas/Error"
    components:
    schemas:
        Pet:
            type: object
            required:
                - id
                - name
            properties:
                id:
                type: integer
                format: int64
                name:
                type: string
                tag:
                type: string
