apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: yelb-ui
  description: Yelb UI App
  tags:
    - javascript
  annotations:
    'backstage.io/kubernetes-label-selector': 'app=yelb-ui,tier=frontend'
    'backstage.io/techdocs-ref': dir:.
  links:
    - url: https://yelb-ui.example.com
      title: 'Yelb UI Information'
      icon: locallibrary
spec:
  type: service
  lifecycle: experimental
  owner: team-a
  system: test1
  dependsOn: [Component:yelb-appserver]
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: test1
  description: YELB Application
  annotations:
    'backstage.io/techdocs-ref': dir:.
spec:
  owner: team-a
  domain: cloud-apps
